fix docker-entrypoint

diff --git a/bin/docker-entrypoint b/bin/docker-entrypoint
--- a/bin/docker-entrypoint
+++ b/bin/docker-entrypoint
@@ -1,14 +1,15 @@
 #!/bin/bash -e
 
-# Enable jemalloc for reduced memory usage and latency.
+# Enable jemalloc for reduced memory usage and latency
 if [ -z "${LD_PRELOAD+x}" ]; then
     LD_PRELOAD=$(find /usr/lib -name libjemalloc.so.2 -print -quit)
     export LD_PRELOAD
 fi
 
 # If running the rails server then create or migrate existing database
-if [ "${@: -2:1}" == "./bin/rails" ] && [ "${@: -1:1}" == "server" ]; then
-  ./bin/rails db:prepare
+if [[ "$*" == *"./bin/rails server"* ]]; then
+  echo "Running database preparation..."
+  ./bin/rails db:prepare || { echo "Database preparation failed"; exit 1; }
 fi
 
-exec "${@}"
+exec "$@"
